modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="slothee"
version="1.0.0"
displayName="Slothee"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MasterSloth"

[[dependencies.slothee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.slothee]]
    modId="GeckoLib API"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

